[trap]
listen_ip="192.168.x.x"
listen_port=162
community_string="public"
community_name="my-area"
trap_file_path="/opt/modules/snmp/trap.txt"
[walk]
agent_list="192.168.x.x"
listen_port=161
community_string="public"
walk_file_path="/opt/modules/snmp/"
oid_number="1.3.6.1"
